version: '3.8'

services:
  #PostgreSQL  
  postgres:
    container_name: db
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shipping-app
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  # backend
  shipping-app-server:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/shipping-app-server
    command: npm start
    working_dir: /usr/src/shipping-app-server
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgres://username:password@postgres:5432/shipping-app
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379