version: '3.8'

services:
  postgres:
    container_name: db
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./db-data/:/var/lib/postgresql/data/